"""Knowledge-base corpus loader.

Reads plain markdown knowledge files from app/rag/knowledge_base/ and splits
them into one Document per markdown section (## heading). Loaded into the
RetrievalIndex at startup (see main.py) so agents can retrieve with source
citations (doc_id = filename stem, title = H1, section = H2).

Prompt 8 -- provenance honesty: every file carries an HTML-comment
front-matter block declaring its source_type:

    <!--
    source_type: public_real | illustrative
    source_url: https://...        (public_real only: the working citation URL)
    source_publisher: ...
    -->

  * public_real    -- a real, publicly published document (e.g. U.S. DOE
                      guidance), generated by scripts/prepare_public_docs.py.
  * illustrative   -- authored FOR this project, modeled on real operational
                      patterns but NOT sourced from Buckman internally.

The distinction is carried in each Document's metadata and surfaces in every
API citation and in the UI; it is never implied.
"""
from __future__ import annotations

import re
from pathlib import Path

from app.rag.retrieval import Document

KB_DIR = Path(__file__).resolve().parent / "knowledge_base"

_FRONT_MATTER_RE = re.compile(r"(?s)<!--\s*(.*?)-->\s*")


def _parse_front_matter(raw: str) -> tuple[dict, str]:
    """Pull the leading HTML-comment front-matter (key: value lines) out of
    the markdown; returns (metadata, body). Absent front matter defaults to
    the honest value: illustrative."""
    metadata: dict = {"source_type": "illustrative"}
    match = _FRONT_MATTER_RE.match(raw.lstrip())
    if match:
        for line in match.group(1).splitlines():
            if ":" in line:
                key, _, value = line.partition(":")
                metadata[key.strip()] = value.strip()
        raw = _FRONT_MATTER_RE.sub("", raw, count=1)
    return metadata, raw


def load_corpus(kb_dir: Path | None = None) -> list[Document]:
    """Load every .md file in the knowledge base as sectioned Documents."""
    directory = kb_dir or KB_DIR
    documents: list[Document] = []
    for path in sorted(directory.glob("*.md")):
        raw = path.read_text(encoding="utf-8")
        metadata, raw = _parse_front_matter(raw)
        title, sections = _split_markdown(raw)
        for heading, body in sections:
            text = body.strip()
            if not text:
                continue
            documents.append(
                Document(
                    doc_id=path.stem,
                    title=title,
                    section=heading,
                    metadata={"source": path.name, **metadata},
                    # Title + section heading go into the indexed text so
                    # queries matching a document name still rank it.
                    text=f"{title} -- {heading}\n{text}",
                )
            )
    if not documents:
        raise RuntimeError(
            f"No knowledge-base documents found in {directory}; the Knowledge "
            "Agent has nothing to retrieve -- check the seed files."
        )
    if not any(d.metadata.get("source_type") == "public_real" for d in documents):
        raise RuntimeError(
            "No public_real knowledge in the corpus; the Prompt 8 provenance "
            "contract requires at least one real public document -- run "
            "scripts/prepare_public_docs.py."
        )
    return documents


def _split_markdown(raw: str) -> tuple[str, list[tuple[str, str]]]:
    """Split markdown into (title, [(section, body), ...]) on H1/H2."""
    title = "Untitled"
    sections: list[tuple[str, str]] = []
    current_heading = "Overview"
    current_lines: list[str] = []

    def flush() -> None:
        sections.append((current_heading, "\n".join(current_lines)))

    for line in raw.splitlines():
        if line.startswith("# ") and not line.startswith("## "):
            title = line[2:].strip()
            continue
        if line.startswith("## "):
            flush()
            current_heading = line[3:].strip()
            current_lines = []
            continue
        current_lines.append(line)
    flush()
    return title, sections
