"""Prompt 8 -- corpus provenance: public_real vs illustrative knowledge.

The honest-corpus contract: every indexed document carries a source_type in
its metadata (parsed from the file's front matter), authored SOPs are
illustrative, and the real public documents (U.S. DOE guidance, generated by
scripts/prepare_public_docs.py) are public_real with a working citation URL.
"""
from __future__ import annotations

from pathlib import Path

import pytest

from app.rag.corpus import KB_DIR, _parse_front_matter, load_corpus
from app.rag.retrieval import RetrievalIndex


def test_every_corpus_document_carries_a_source_type() -> None:
    docs = load_corpus()
    assert docs, "corpus must not be empty"
    for d in docs:
        assert d.metadata.get("source_type") in ("public_real", "illustrative"), (
            f"{d.doc_id} has no honest source_type -- provenance would be implied"
        )


def test_authored_sops_are_illustrative() -> None:
    docs = load_corpus()
    sops = {d.doc_id for d in docs if d.doc_id.startswith("SOP-")}
    assert sops, "authored SOPs missing from the corpus"
    for d in docs:
        if d.doc_id.startswith("SOP-"):
            assert d.metadata["source_type"] == "illustrative"


def test_public_real_documents_carry_working_citation_urls() -> None:
    docs = load_corpus()
    public = [d for d in docs if d.metadata["source_type"] == "public_real"]
    assert public, "no public_real knowledge -- run scripts/prepare_public_docs.py"
    by_doc: dict[str, list] = {}
    for d in public:
        by_doc.setdefault(d.doc_id, []).append(d)
    for doc_id, chunks in by_doc.items():
        urls = {c.metadata.get("source_url", "") for c in chunks}
        assert all(u.startswith("https://") for u in urls), doc_id
        assert not any("buckman" in u.lower() for u in urls), (
            f"{doc_id}: citation must point at the PUBLIC source, never anything internal"
        )


def test_public_docs_are_retrievable_by_pump_and_cooling_queries() -> None:
    docs = load_corpus()
    index = RetrievalIndex()
    index.index(docs)
    for query in ("pump maintenance vibration bearing", "cooling tower blowdown cycles of concentration"):
        hits = index.search(query, top_k=4)
        assert hits, f"no retrieval hits for {query!r}"
        assert any(h.metadata["source_type"] == "public_real" for h in hits), (
            f"public_real documents must rank for {query!r}"
        )


def test_front_matter_defaults_to_illustrative() -> None:
    metadata, body = _parse_front_matter("# T\n\n## S\n\nbody")
    assert metadata == {"source_type": "illustrative"}
    assert "<!--" not in body and "source_type" not in body


def test_front_matter_parses_public_real_metadata() -> None:
    raw = (
        "<!--\nsource_type: public_real\n"
        "source_url: https://www.csb.gov/mfg-chemical-inc-toxic-gas-release/\n"
        "-->\n# Title\n\n## Section\n\nbody text"
    )
    metadata, body = _parse_front_matter(raw)
    assert metadata["source_type"] == "public_real"
    assert metadata["source_url"] == "https://www.csb.gov/mfg-chemical-inc-toxic-gas-release/"
    assert "source_type" not in body and "## Section" in body


def test_generated_kb_files_carry_front_matter() -> None:
    """The committed KB files produced by scripts/prepare_public_docs.py must
    declare their provenance in-file (offline check; --check verifies too)."""
    for name in ("PUB-DOE-FEMP-COOLING-TOWER.md", "PUB-DOE-PUMP-SOURCEBOOK.md"):
        path = KB_DIR / name
        if not path.exists():
            pytest.fail(
                f"{name} missing -- run scripts/prepare_public_docs.py on a "
                "machine with network access (documented CI tradeoff, see "
                "docs/real-data-sources.md)"
            )
        head = path.read_text(encoding="utf-8")[:400]
        assert "source_type: public_real" in head, name
        assert "https://" in head, name
