"""Grounded "Why?" Q&A endpoint (Prompt 6).

The operator asks a question about ONE incident. The answer is generated by
the same llm_client the other agents use, but the context is restricted to
what is ALREADY on the incident record (root cause + evidence + risk +
recommendation). Nothing new is retrieved and nothing external is touched:

  * No new evidence retrieval -- retrieval is the Knowledge Agent's job.
  * No tool calling -- this is explanation, not planning or action.

Grounding is enforced twice:
  1. The system prompt forbids answering outside the incident record and
     requires the literal fallback sentence for out-of-scope questions.
  2. Bullet lines in the answer are re-validated with the Root-Cause Agent's
     deterministic citation checker (`_validate_point`), so a bullet citing a
     sensor / SOP id / historical incident that is NOT on the record is
     rejected; if any bullet fails, the caller gets the same honest fallback.
     Prompt instructions are never trusted on their own.
"""
from __future__ import annotations

from fastapi import APIRouter, Depends, HTTPException

from app.agents.root_cause.agent import _validate_point
from app.core.db import get_incident
from app.core.llm_client import get_llm_client
from app.core.logging_config import get_logger
from app.core.security import Principal, ensure_role, ensure_site, get_rbac_policy, require_principal

logger = get_logger(__name__)

router = APIRouter(prefix="/api/v1/incidents", tags=["ask"])

MAX_QUESTION_CHARS = 500
MAX_ANSWER_CHARS = 1500
INSUFFICIENT = "I don't have evidence for that."

SYSTEM_PROMPT = """You are the assistant embedded in an industrial anomaly-investigation \
view. You answer operator questions about ONE specific incident. You are given the incident's \
recorded root cause, its cited evidence points, the risk assessment, and the recommendation.

ABSOLUTE RULES:
1. Answer ONLY from that material. Do not use outside knowledge, do not invent readings, ids, \
or causes, and do not speculate.
2. When you state a fact, put it on a bullet line ("- ...") and name its source explicitly: \
a sensor reading by name (e.g. flow_rate), an SOP id in brackets like [SOP citation SOP-XXX-NNN], \
or a historical incident reference like [historical incident HIST-YYYY-NNNN].
3. If the question is about anything not contained in the material, or the material does not \
support an answer, reply with exactly: "I don't have evidence for that." and nothing else.
4. Keep answers under 100 words."""


def _build_context(incident: dict) -> str:
    """Serialize ONLY the incident's recorded data as the model's context."""
    root_cause = incident.get("rootCause") or {}
    evidence = incident.get("retrievedEvidence") or {}
    risk = incident.get("risk") or {}
    recommendation = incident.get("recommendation") or {}
    anomaly_summary = incident.get("anomalySummary") or {"sensors": []}

    lines = ["DETECTED ANOMALY (as recorded at detection time):"]
    sensors = anomaly_summary.get("sensors") or []
    for s in sensors:
        lines.append(
            f"- sensor: {s.get('sensor_type')} value={s.get('value')}{s.get('unit') or ''} "
            f"(normal {s.get('normal_min')}–{s.get('normal_max')}; {s.get('reason') or 'outside normal range'})"
        )
    if not sensors:
        lines.append("- (summary unavailable)")

    lines.append("")
    lines.append("RECORDED ROOT CAUSE:")
    if root_cause.get("hypothesis"):
        lines.append(f"- {root_cause['hypothesis']} (confidence {root_cause.get('confidence')}%)")
        for point in root_cause.get("citedEvidence") or []:
            lines.append(f"  - {point.get('text')}")
    else:
        lines.append("- (diagnosis not complete yet)")

    lines.append("")
    lines.append("RECORDED EVIDENCE:")
    sop_chunks = evidence.get("sop_chunks") or []
    matched_history = evidence.get("matched_history") or []
    for c in sop_chunks:
        lines.append(
            f"- SOP [{c.get('docId')}] {c.get('title')} -- {c.get('section')} "
            f"(score {c.get('score')}): {str(c.get('excerpt', ''))[:280]}"
        )
    for h in matched_history:
        lines.append(
            f"- HIST [{h.get('source')}] {h.get('equipmentName')} ({str(h.get('occurredAt', ''))[:10]}): "
            f"symptoms={h.get('symptoms')}; root cause: {h.get('rootCause')}; "
            f"resolution: {h.get('resolution')}"
        )
    if not sop_chunks and not matched_history:
        lines.append("- (none yet)")

    lines.append("")
    lines.append("RISK ASSESSMENT:")
    if risk.get("severity"):
        consequences = ", ".join(
            str(c.get("consequence") or c.get("name") or "?")
            for c in risk.get("consequences") or []
        ) or "(none listed)"
        lines.append(
            f"- severity {risk['severity']}, HITL level {risk.get('hitlLevel')} "
            f"(consequences: {consequences})"
        )
    else:
        lines.append("- (not assessed yet)")

    lines.append("")
    lines.append("RECOMMENDATION:")
    if recommendation.get("rationale") or recommendation.get("actions"):
        lines.append(f"- rationale: {recommendation.get('rationale') or '(none)'}")
        for a in recommendation.get("actions") or []:
            lines.append(f"  - action: {a.get('description') or a.get('action') or '?'}")
    else:
        lines.append("- (not generated yet)")

    return "\n".join(lines)


def _no_evidence_answer(question: str, reason: str) -> dict:
    """The honest fallback: fixed wording, nothing model-generated."""
    logger.info("Grounded Q&A fallback (%s)", reason)
    return {
        "question": question,
        "answer": INSUFFICIENT,
        "citations": [],
        "grounded": False,
        "model": "none",
        "provider": "none",
        "askedAt": None,
    }


async def _grounded_answer(incident: dict, question: str) -> dict:
    """One-shot grounded answer: no new retrieval, no tools, single LLM round
    trip whose bullet lines are citation-verified against the incident record."""
    anomaly_summary = incident.get("anomalySummary") or {"sensors": []}
    evidence = incident.get("retrievedEvidence") or {}

    user_prompt = (
        "INCIDENT CONTEXT (the ONLY material you may use):\n"
        + _build_context(incident)
        + f"\n\nOPERATOR QUESTION: {question}\n"
        + 'If this question cannot be answered from the context above, reply with '
        + 'exactly: "I don\'t have evidence for that."'
    )

    response = await get_llm_client().generate(SYSTEM_PROMPT, user_prompt)
    answer = (response.content or "").strip()

    if answer.lower().startswith("i don't have evidence"):
        return _no_evidence_answer(question, "model declined: outside recorded evidence")

    # Deterministic re-validation of every bullet claim (mirror of the
    # Root-Cause Agent's enforcement -- prompt rules alone are not trusted).
    cited: list[dict] = []
    failed = 0
    for raw_line in answer.splitlines():
        stripped = raw_line.strip()
        if not stripped or stripped[0] not in "-*•":
            continue  # prose lines are narrative, not checkable claims
        point = stripped.lstrip("-*• ").strip()
        if not point:
            continue
        verdict = _validate_point(point, anomaly_summary, evidence)
        if verdict is None:
            failed += 1
            logger.warning("Grounded answer bullet failed citation check: %r", point)
        else:
            cited.append({"type": verdict[0], "ref": verdict[1], "text": point})

    if failed > 0:
        # Any unverifiable claim poisons the whole answer: never surface it.
        return _no_evidence_answer(
            question, f"{failed} bullet line(s) failed citation verification"
        )

    return {
        "question": question,
        "answer": answer[:MAX_ANSWER_CHARS],
        "citations": cited,
        "grounded": bool(cited),
        "model": response.model,
        "provider": response.provider,
        "askedAt": None,  # filled by the route
    }


@router.post("/{incident_id}/ask")
async def ask_about_incident(
    incident_id: str, body: dict, principal: Principal = Depends(require_principal)
) -> dict:
    """Grounded operator Q&A for ONE incident.

    The model sees only the incident's recorded root cause + evidence + risk +
    recommendation; answers citing anything else are rejected deterministically
    and the endpoint returns the fixed 'I don't have evidence for that.'
    fallback instead of a plausible-sounding hallucination.

    Prompt 7: token-validated and site-scoped like every other route; the
    RBAC table decides which roles may use the chat (all three demo roles).
    """
    ensure_role(principal, get_rbac_policy().chat_roles, "use grounded Q&A")
    incident = await get_incident(incident_id)
    if incident is None:
        raise HTTPException(status_code=404, detail="incident not found")
    ensure_site(principal, incident["siteId"])

    question = str(body.get("question") or "").strip()
    if not question:
        raise HTTPException(status_code=422, detail="question is required")
    if len(question) > MAX_QUESTION_CHARS:
        raise HTTPException(status_code=422, detail=f"question must be <= {MAX_QUESTION_CHARS} characters")

    result = await _grounded_answer(incident, question)
    from datetime import datetime, timezone

    result["askedAt"] = datetime.now(timezone.utc).isoformat()
    logger.info(
        "Grounded Q&A for incident %s (provider=%s model=%s grounded=%s)",
        incident_id, result["provider"], result["model"], result["grounded"],
    )
    return result
